# Site settings
author: Mikael Kaya
title: Kaya the Writer and Coder
header-img: img/home-bg.png
email: kayaswork@gmail.com
copyright_name: Mikael Kaya
description: > # this means to ignore newlines until "baseurl:"
  With a love for writing, copywriting, & coding.. imagine the websites.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kayathewriter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
